spring:
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 20000ms
    password: chen
    jedis:
      pool:
        #最小空闲连接
        min-idle: 0
        #最大空闲连接
        max-idle: 8
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms