package com.example.demo.test.Spring.dao;

import com.example.demo.test.Spring.entity.AdapterApi;
import com.example.demo.test.Spring.entity.AdapterApiExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

import javax.annotation.Resource;


public interface AdapterApiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adapter_api
     *
     * @mbg.generated
     */
    long countByExample(AdapterApiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adapter_api
     *
     * @mbg.generated
     */
    int deleteByExample(AdapterApiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adapter_api
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer apiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adapter_api
     *
     * @mbg.generated
     */
    int insert(AdapterApi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adapter_api
     *
     * @mbg.generated
     */
    int insertSelective(AdapterApi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adapter_api
     *
     * @mbg.generated
     */
    List<AdapterApi> selectByExample(AdapterApiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adapter_api
     *
     * @mbg.generated
     */
    AdapterApi selectByPrimaryKey(Integer apiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adapter_api
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AdapterApi record, @Param("example") AdapterApiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adapter_api
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AdapterApi record, @Param("example") AdapterApiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adapter_api
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AdapterApi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adapter_api
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AdapterApi record);
}