package com.example.demo.test.Spring.dao;

import com.example.demo.test.Spring.entity.Backup;
import com.example.demo.test.Spring.entity.BackupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BackupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backup
     *
     * @mbg.generated
     */
    long countByExample(BackupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backup
     *
     * @mbg.generated
     */
    int deleteByExample(BackupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backup
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer backupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backup
     *
     * @mbg.generated
     */
    int insert(Backup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backup
     *
     * @mbg.generated
     */
    int insertSelective(Backup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backup
     *
     * @mbg.generated
     */
    List<Backup> selectByExampleWithBLOBs(BackupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backup
     *
     * @mbg.generated
     */
    List<Backup> selectByExample(BackupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backup
     *
     * @mbg.generated
     */
    Backup selectByPrimaryKey(Integer backupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backup
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Backup record, @Param("example") BackupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backup
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") Backup record, @Param("example") BackupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backup
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Backup record, @Param("example") BackupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backup
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Backup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backup
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Backup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backup
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Backup record);
}