package com.example.demo.test.Spring.entity;

import java.io.Serializable;
import java.util.Date;

public class Backup implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backup.backUp_id
     *
     * @mbg.generated
     */
    private Integer backupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backup.facility_id
     *
     * @mbg.generated
     */
    private Integer facilityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backup.studyUid
     *
     * @mbg.generated
     */
    private String studyuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backup.modality
     *
     * @mbg.generated
     */
    private String modality;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backup.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backup.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backup.dataJson
     *
     * @mbg.generated
     */
    private String datajson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table backup
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backup.backUp_id
     *
     * @return the value of backup.backUp_id
     *
     * @mbg.generated
     */
    public Integer getBackupId() {
        return backupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backup.backUp_id
     *
     * @param backupId the value for backup.backUp_id
     *
     * @mbg.generated
     */
    public void setBackupId(Integer backupId) {
        this.backupId = backupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backup.facility_id
     *
     * @return the value of backup.facility_id
     *
     * @mbg.generated
     */
    public Integer getFacilityId() {
        return facilityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backup.facility_id
     *
     * @param facilityId the value for backup.facility_id
     *
     * @mbg.generated
     */
    public void setFacilityId(Integer facilityId) {
        this.facilityId = facilityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backup.studyUid
     *
     * @return the value of backup.studyUid
     *
     * @mbg.generated
     */
    public String getStudyuid() {
        return studyuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backup.studyUid
     *
     * @param studyuid the value for backup.studyUid
     *
     * @mbg.generated
     */
    public void setStudyuid(String studyuid) {
        this.studyuid = studyuid == null ? null : studyuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backup.modality
     *
     * @return the value of backup.modality
     *
     * @mbg.generated
     */
    public String getModality() {
        return modality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backup.modality
     *
     * @param modality the value for backup.modality
     *
     * @mbg.generated
     */
    public void setModality(String modality) {
        this.modality = modality == null ? null : modality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backup.time
     *
     * @return the value of backup.time
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backup.time
     *
     * @param time the value for backup.time
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backup.type
     *
     * @return the value of backup.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backup.type
     *
     * @param type the value for backup.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backup.dataJson
     *
     * @return the value of backup.dataJson
     *
     * @mbg.generated
     */
    public String getDatajson() {
        return datajson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backup.dataJson
     *
     * @param datajson the value for backup.dataJson
     *
     * @mbg.generated
     */
    public void setDatajson(String datajson) {
        this.datajson = datajson == null ? null : datajson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backup
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Backup other = (Backup) that;
        return (this.getBackupId() == null ? other.getBackupId() == null : this.getBackupId().equals(other.getBackupId()))
            && (this.getFacilityId() == null ? other.getFacilityId() == null : this.getFacilityId().equals(other.getFacilityId()))
            && (this.getStudyuid() == null ? other.getStudyuid() == null : this.getStudyuid().equals(other.getStudyuid()))
            && (this.getModality() == null ? other.getModality() == null : this.getModality().equals(other.getModality()))
            && (this.getTime() == null ? other.getTime() == null : this.getTime().equals(other.getTime()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getDatajson() == null ? other.getDatajson() == null : this.getDatajson().equals(other.getDatajson()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backup
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getBackupId() == null) ? 0 : getBackupId().hashCode());
        result = prime * result + ((getFacilityId() == null) ? 0 : getFacilityId().hashCode());
        result = prime * result + ((getStudyuid() == null) ? 0 : getStudyuid().hashCode());
        result = prime * result + ((getModality() == null) ? 0 : getModality().hashCode());
        result = prime * result + ((getTime() == null) ? 0 : getTime().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getDatajson() == null) ? 0 : getDatajson().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backup
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", backupId=").append(backupId);
        sb.append(", facilityId=").append(facilityId);
        sb.append(", studyuid=").append(studyuid);
        sb.append(", modality=").append(modality);
        sb.append(", time=").append(time);
        sb.append(", type=").append(type);
        sb.append(", datajson=").append(datajson);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}